@startuml
title WarmHouse context diagram

!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "A user of the warmhouse system")

System(WarmHouse, "WarmHouse System", "Managing warm system")

System_Ext(sensors, "In-house sensors", "Sensors manages temperature in house")

Rel(user, WarmHouse, "uses the system")
Rel(WarmHouse, sensors, "manages sensors")

@enduml